version: '3.8'

services:
  # PostgreSQL Database for local development
  postgres_local:
    image: postgres:15
    container_name: sda_postgres_local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=sda_local_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
      # Initialize with some sample data if needed
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - sda_local_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching (optional but recommended)
  redis_local:
    image: redis:7-alpine
    container_name: sda_redis_local
    command: redis-server --save 60 1 --loglevel warning --requirepass redis123
    ports:
      - "6379:6379"
    volumes:
      - redis_local_data:/data
    networks:
      - sda_local_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  sda_local_network:
    driver: bridge

volumes:
  postgres_local_data:
  redis_local_data: