[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["app"]

[project]
name = "sda"
version = "0.1.0"
description = "SDA API"
requires-python = ">=3.11"
