"""add_multilingual_support

Revision ID: 10513c7e8c3d
Revises: frontend_compat_2025
Create Date: 2025-10-03 09:51:49.847355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10513c7e8c3d'
down_revision: Union[str, None] = 'frontend_compat_2025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('title_en', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('title_az', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('title_ru', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('excerpt_en', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('excerpt_az', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('excerpt_ru', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('content_en', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('content_az', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('content_ru', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('summary_en', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('summary_az', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('summary_ru', sa.Text(), nullable=True))
    op.alter_column('news', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('news', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('news', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('news', 'author',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('news', 'read_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_news_slug'), table_name='news')
    op.create_index('ix_news_slug', 'news', ['slug'], unique=False)
    op.create_unique_constraint(None, 'news', ['slug'])
    op.drop_column('news', 'date')
    op.add_column('projects', sa.Column('title_en', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('title_az', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('title_ru', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('description_az', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('description_ru', sa.Text(), nullable=True))
    op.alter_column('projects', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_projects_order'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.create_index('ix_projects_slug', 'projects', ['slug'], unique=False)
    op.create_index('ix_projects_title_az', 'projects', ['title_az'], unique=False)
    op.create_index('ix_projects_title_en', 'projects', ['title_en'], unique=False)
    op.create_index('ix_projects_title_ru', 'projects', ['title_ru'], unique=False)
    op.create_unique_constraint(None, 'projects', ['slug'])
    op.drop_column('projects', 'order')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'services')
    op.add_column('services', sa.Column('name_en', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('name_az', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('name_ru', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('description_az', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('description_ru', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('hero_text_en', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('hero_text_az', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('hero_text_ru', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('meta_title_en', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('meta_title_az', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('meta_title_ru', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('meta_description_en', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('meta_description_az', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('meta_description_ru', sa.Text(), nullable=True))
    op.alter_column('services', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('services', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.create_index('ix_services_slug', 'services', ['slug'], unique=False)
    op.create_unique_constraint(None, 'services', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='unique')
    op.drop_index('ix_services_slug', table_name='services')
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
    op.alter_column('services', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('services', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('services', 'meta_description_ru')
    op.drop_column('services', 'meta_description_az')
    op.drop_column('services', 'meta_description_en')
    op.drop_column('services', 'meta_title_ru')
    op.drop_column('services', 'meta_title_az')
    op.drop_column('services', 'meta_title_en')
    op.drop_column('services', 'hero_text_ru')
    op.drop_column('services', 'hero_text_az')
    op.drop_column('services', 'hero_text_en')
    op.drop_column('services', 'description_ru')
    op.drop_column('services', 'description_az')
    op.drop_column('services', 'description_en')
    op.drop_column('services', 'name_ru')
    op.drop_column('services', 'name_az')
    op.drop_column('services', 'name_en')
    op.add_column('projects', sa.Column('services', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_index('ix_projects_title_ru', table_name='projects')
    op.drop_index('ix_projects_title_en', table_name='projects')
    op.drop_index('ix_projects_title_az', table_name='projects')
    op.drop_index('ix_projects_slug', table_name='projects')
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index(op.f('ix_projects_order'), 'projects', ['order'], unique=False)
    op.alter_column('projects', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('projects', 'description_ru')
    op.drop_column('projects', 'description_az')
    op.drop_column('projects', 'description_en')
    op.drop_column('projects', 'title_ru')
    op.drop_column('projects', 'title_az')
    op.drop_column('projects', 'title_en')
    op.add_column('news', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_index('ix_news_slug', table_name='news')
    op.create_index(op.f('ix_news_slug'), 'news', ['slug'], unique=True)
    op.alter_column('news', 'read_time',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('news', 'author',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('news', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('news', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('news', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('news', 'summary_ru')
    op.drop_column('news', 'summary_az')
    op.drop_column('news', 'summary_en')
    op.drop_column('news', 'content_ru')
    op.drop_column('news', 'content_az')
    op.drop_column('news', 'content_en')
    op.drop_column('news', 'excerpt_ru')
    op.drop_column('news', 'excerpt_az')
    op.drop_column('news', 'excerpt_en')
    op.drop_column('news', 'title_ru')
    op.drop_column('news', 'title_az')
    op.drop_column('news', 'title_en')
    # ### end Alembic commands ###
