"""Add icon_url to services and image_url to work_processes

Revision ID: add_image_fields
Revises: ea7a667484f5
Create Date: 2025-08-26 03:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_image_fields'
down_revision = 'ea7a667484f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('icon_url', sa.Text(), nullable=True))
    op.add_column('work_processes', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_processes', 'image_url')
    op.drop_column('services', 'icon_url')
    # ### end Alembic commands ###
