"""add_multilingual_fields_to_remaining_models

Revision ID: bc1b6999c0c3
Revises: 10513c7e8c3d
Create Date: 2025-10-03 10:59:47.030948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1b6999c0c3'
down_revision: Union[str, None] = '10513c7e8c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('experience_en', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('experience_az', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('experience_ru', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('project_count_en', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('project_count_az', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('project_count_ru', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('members_en', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('members_az', sa.Text(), nullable=True))
    op.add_column('about', sa.Column('members_ru', sa.Text(), nullable=True))
    op.alter_column('about', 'experience',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('about', 'project_count',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('about', 'members',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('approaches', sa.Column('title_en', sa.Text(), nullable=True))
    op.add_column('approaches', sa.Column('title_az', sa.Text(), nullable=True))
    op.add_column('approaches', sa.Column('title_ru', sa.Text(), nullable=True))
    op.add_column('approaches', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('approaches', sa.Column('description_az', sa.Text(), nullable=True))
    op.add_column('approaches', sa.Column('description_ru', sa.Text(), nullable=True))
    op.alter_column('approaches', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('partners', sa.Column('title_en', sa.Text(), nullable=True))
    op.add_column('partners', sa.Column('title_az', sa.Text(), nullable=True))
    op.add_column('partners', sa.Column('title_ru', sa.Text(), nullable=True))
    op.add_column('partners', sa.Column('button_text_en', sa.Text(), nullable=True))
    op.add_column('partners', sa.Column('button_text_az', sa.Text(), nullable=True))
    op.add_column('partners', sa.Column('button_text_ru', sa.Text(), nullable=True))
    op.alter_column('partners', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('property_sectors', sa.Column('title_en', sa.Text(), nullable=True))
    op.add_column('property_sectors', sa.Column('title_az', sa.Text(), nullable=True))
    op.add_column('property_sectors', sa.Column('title_ru', sa.Text(), nullable=True))
    op.add_column('property_sectors', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('property_sectors', sa.Column('description_az', sa.Text(), nullable=True))
    op.add_column('property_sectors', sa.Column('description_ru', sa.Text(), nullable=True))
    op.alter_column('property_sectors', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('property_sectors_title_key'), 'property_sectors', type_='unique')
    op.add_column('team_members', sa.Column('full_name_en', sa.Text(), nullable=True))
    op.add_column('team_members', sa.Column('full_name_az', sa.Text(), nullable=True))
    op.add_column('team_members', sa.Column('full_name_ru', sa.Text(), nullable=True))
    op.add_column('team_members', sa.Column('role_en', sa.Text(), nullable=True))
    op.add_column('team_members', sa.Column('role_az', sa.Text(), nullable=True))
    op.add_column('team_members', sa.Column('role_ru', sa.Text(), nullable=True))
    op.alter_column('team_members', 'full_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('work_processes', sa.Column('title_en', sa.Text(), nullable=True))
    op.add_column('work_processes', sa.Column('title_az', sa.Text(), nullable=True))
    op.add_column('work_processes', sa.Column('title_ru', sa.Text(), nullable=True))
    op.add_column('work_processes', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('work_processes', sa.Column('description_az', sa.Text(), nullable=True))
    op.add_column('work_processes', sa.Column('description_ru', sa.Text(), nullable=True))
    op.alter_column('work_processes', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_processes', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('work_processes', 'description_ru')
    op.drop_column('work_processes', 'description_az')
    op.drop_column('work_processes', 'description_en')
    op.drop_column('work_processes', 'title_ru')
    op.drop_column('work_processes', 'title_az')
    op.drop_column('work_processes', 'title_en')
    op.alter_column('team_members', 'full_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('team_members', 'role_ru')
    op.drop_column('team_members', 'role_az')
    op.drop_column('team_members', 'role_en')
    op.drop_column('team_members', 'full_name_ru')
    op.drop_column('team_members', 'full_name_az')
    op.drop_column('team_members', 'full_name_en')
    op.create_unique_constraint(op.f('property_sectors_title_key'), 'property_sectors', ['title'], postgresql_nulls_not_distinct=False)
    op.alter_column('property_sectors', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('property_sectors', 'description_ru')
    op.drop_column('property_sectors', 'description_az')
    op.drop_column('property_sectors', 'description_en')
    op.drop_column('property_sectors', 'title_ru')
    op.drop_column('property_sectors', 'title_az')
    op.drop_column('property_sectors', 'title_en')
    op.alter_column('partners', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('partners', 'button_text_ru')
    op.drop_column('partners', 'button_text_az')
    op.drop_column('partners', 'button_text_en')
    op.drop_column('partners', 'title_ru')
    op.drop_column('partners', 'title_az')
    op.drop_column('partners', 'title_en')
    op.alter_column('approaches', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('approaches', 'description_ru')
    op.drop_column('approaches', 'description_az')
    op.drop_column('approaches', 'description_en')
    op.drop_column('approaches', 'title_ru')
    op.drop_column('approaches', 'title_az')
    op.drop_column('approaches', 'title_en')
    op.alter_column('about', 'members',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('about', 'project_count',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('about', 'experience',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('about', 'members_ru')
    op.drop_column('about', 'members_az')
    op.drop_column('about', 'members_en')
    op.drop_column('about', 'project_count_ru')
    op.drop_column('about', 'project_count_az')
    op.drop_column('about', 'project_count_en')
    op.drop_column('about', 'experience_ru')
    op.drop_column('about', 'experience_az')
    op.drop_column('about', 'experience_en')
    # ### end Alembic commands ###
